USERMODULES_DIR := $(USERMOD_DIR)

# Add all C files to SRC_USERMOD.
SRC_USERMOD += $(USERMODULES_DIR)/mp_srmulitplexer.c
SRC_USERMOD += $(USERMODULES_DIR)/srmulitplexer.c

CFLAGS_USERMOD += -I$(USERMODULES_DIR)